### ISSUE TITLE
solga-swagger-0.1.0.1 release tarball lacks a Setup.hs file

### ISSUE THREAD

**Issue by peti** [chpatrick/solga#7]
Please add a `Setup.hs` to the release archive on Hackage.

**Comment by peti** [comment]
Why did you close this issue?

**Comment by chpatrick** [comment]
Hi Peter,

It's fixed, isn't it?

Patrick

**Comment by peti** [comment]
I don't know. I'd have to check ...

**Comment by chpatrick** [comment]
I closed it because I fixed it in e3a9fd9b5b4147f753822eb97c8a87c982b61b82.

**Comment by peti** [comment]
Ah, very cool. Thank you.
